### ISSUE TITLE
Cannot create a tensor proto whose content is larger than 2GB

### ISSUE THREAD

**Issue by ahmedmsoliman96** [cgorman/tensorflow-som#4]
when i tried to call SelfOrganizingMap initialization with input_tensor equalt to an array that has size greater than 2 GB i got this error. can i do any thing to fix this issue ? 

this is how i tried to call the functions 

som = tf_som.SelfOrganizingMap(300, 128, 2, gpus=1,input_tensor=descriptors)
som.train(descriptors.shape[0])

descriptors is a matrix of size (6312149, 128) and has size of nearly 3 GB 

this is the traceback generated by pycharm 2018.2.4

Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper preferred_dtype=default_dtype)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 506, in make_tensor_proto
    "Cannot create a tensor proto whose content is larger than 2GB.")

ValueError: Cannot create a tensor proto whose content is larger than 2GB.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 506, in make_tensor_proto
    "Cannot create a tensor proto whose content is larger than 2GB.")

ValueError: Cannot create a tensor proto whose content is larger than 2GB.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Pattern Recognition v2/sift.py", line 405, in <module>
    som = tf_som.SelfOrganizingMap(300, 128, 2, gpus=1,input_tensor=descriptors)

  File "C:\Pattern Recognition v2\tf_som.py", line 112, in __init__
    self._initialize_tf_graph()

  File "C:\Pattern Recognition v2\tf_som.py", line 166, in _initialize_tf_graph
    tower_updates.append(self._tower_som())

  File "C:\Pattern Recognition v2\tf_som.py", line 219, in _tower_som
    self._input = tf.identity(self._input_tensor)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4103, in identity
    "Identity", input=input, name=name)

  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))

ValueError: Tried to convert 'input' to a tensor and failed. Error: Cannot create a tensor proto whose content is larger than 2GB.

**Comment by cgorman** [comment]
Hi Ahmed, I think you need to use the tensorflow datasets module to avoid this error. If you take a look at [these lines](https://github.com/cgorman/tensorflow-som/blob/e69ed79357d9d7d4ac846630940a0f57551caf41/example.py#L69-L73) it might be helpful. This way I think it acts more like a memory map and only loads the data into the tensor when it needs to. 

Hope this helps,
Chris
